name: Test on Test branch from Feature branch.

on:
  push:
    branches:
      - convictional-1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: convictional-1
      - name: print branch name
        run: |
          echo "The branch name is ${{ github.ref }}"
              
      - name: Cache Depenedencies
        uses: actions/setup-java@v2
        with:
           java-version: '11'
           distribution: 'adopt'
           cache: maven
      - name: Build with maven
        run: |      
         mvn -B clean package -s .maven/settings.xml
        
    
      - name: Stamp artifact file name with commit hash
        run: |
          artifactName1=$(ls target/*.jar | head -1)
          commitHash=$(git rev-parse --short "$GITHUB_SHA")
          artifactName2=$(ls target/*.jar | head -1 | sed "s/.jar/-$commitHash-${{ github.run_number }}.jar/g")
          mv $artifactName1 $artifactName2
        
      - name: Print Run Number
        run: |
          echo "The run number is ${{ github.run_number }}"    
      - name: List Files
        run: |  
         pwd
         ls -lart
         ls -lart ./target/    
    
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/*.jar
          
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN_TEST }}
        with:
          tag_name: v1.0.0
          release_name: Release 1.0.0
          draft: false
          prerelease: false
          
      - name: Upload artifacts to Repository B
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/*.jar
          repository: Mayureshgithub/Test_private_repo      # Replace with the owner and repository name of Repository B
          token: ${{ secrets.PAT_TOKEN_TEST }}      
          
      - name: sleep
        run: |
         sleep 20
          
      - name: Trigger Second Workflow.
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: Mayureshgithub
          repo: Test_private_repo
          github_token: ${{ secrets.PAT_TOKEN_TEST }}
          workflow_file_name: convictional-2.yml
          ref: convictional-2
          
          
#       - name: Trigger Test Workflow
#         uses: peter-evans/repository-dispatch@v1
#         with:
#           token: ${{ secrets.PAT_TOKEN_TEST }}
#           repository: Mayureshgithub/Test_private_repo
#           event-type: test-workflow
#           ref: test
#           client-payload: '{"build_id": "${{ github.run_id }}"}'
